### ISSUE TITLE
multiple definition in header-only library

### ISSUE THREAD

**Issue by rochadt** [tdv/redis-cpp#13]
I'm attempting to use the header only import of the `c++11` branch (basically as described in https://github.com/tdv/redis-cpp/issues/4#issuecomment-667507438). I've included the macro definition `#define REDISCPP_HEADER_ONLY`, but when I compile it I get the following error:
```
multiple definition of `rediscpp::resp::deserialization::get_mark(std::istream&)';
```
I even tried using `#ifndef` but the issue persisted. I'm not sure what causes this but, if I change:
https://github.com/tdv/redis-cpp/blob/a7302a31ce5b19e6f58ff03957c73acc882d78cf/include/redis-cpp/resp/deserialization.h#L36
to:
```
[[nodiscard]]
inline char get_mark(std::istream &stream)
{
```
It resolves the issue. I'm not sure if this is the correct way to fix this though. Can anyone confirm this issue / resolution?

**Comment by tdv** [comment]
Hi. Thanks for addressing the issue.
Yes, your way is the most correct in this case.
I've just committed a fix into C++11 backport.

**Comment by rochadt** [comment]
@tdv Thank you for including the fix!
