### ISSUE TITLE
Fatal error C1189: #error:  "RedisCpp. Requires C++ 17 or higher."

### ISSUE THREAD

**Issue by Domigome** [tdv/redis-cpp#17]
When building the C++11 branch I got this error. I'm using Visual Studio 2019.

CMakeList has the flag set (STD_CXX "c++11") yet I don't know why this happens. I have tried setting the project settings to use ISO C++11 but nothing changes.

Any hint?

**Comment by tdv** [comment]
Hello.
Try:
- clone the project
- switch for c++11 branch
- generate your new VC solution
- 
It might solve your issue, but I'm not sure. I've never tried to build this one under Win and overall CMake files have been created for and within Linux.

Good luck.

PS. If you deal isssue and make pullrequest, it'll be the best ending of this issue.

**Comment by tdv** [comment]
Hi again.

I've just caught in mind another idea: you can use the library as a header-only library. That will completely solve your issue.

Steps:
- clone specific branch (master for C++ 17 or c++11 for C++ 11)
- add all headers of the library into your VC solution, been saving file's structure of the library
- add the boost library to project
- in the code before including the library, define the macros REDISCPP_HEADER_ONLY like in the samples (in README.md)

It'll work without any problems.

Good luck.

Regards.
