### ISSUE TITLE
how to get pattern/channel info in pub/sub.

### ISSUE THREAD

**Issue by rahulsharma11** [tdv/redis-cpp#19]
Hi, I am using redis-python for publishing the data which is publishing the data in raw format such as -
{'type': 'pmessage',
 'pattern': 'channel-*',
 'channel': 'channel',
 'data': 'data'}.

When i receive it with redis-cpp subscribe, i get all the information but only values (not keys) also as separate/discrete messages like-
pmessage
channel-*
channel
data

if i underline the specific code segmant - 
 **[&print_message] (rediscpp::resp::deserialization::array const &arr)
        {
            for (auto const &i : arr.get()){
                print_message(i);
         }**
Here i can see the whole array is processed line-by-line and string data is extracted for each line....

My question is can i get the whole array as in json/string format so that i can use that in my way?
Thanks.

**Comment by tdv** [comment]
Hi.

There is only basic redis protocol covering and low-level access for command executing via C++ and no more. There are no any features --like convert to JSON-- available. (Also see the #20 )

Regards.

**Comment by rahulsharma11** [comment]
ok thanks.
