### ISSUE TITLE
SEG SIGNAL when use reset and AUTH enabled 

### ISSUE THREAD

**Issue by roniinterconetica** [tdv/redis-cpp#25]
Hi I have found a possible issue , for example using this project I can do the following : 

```
	auto stream = rediscpp::make_stream("127.0.0.1", "6379");
	rediscpp::value response = rediscpp::execute( (*stream), "select", "1");

        if( response.is_error_message() )
	{
		cout << response.as_error_message() << endl;
	}
	else
	{
		cout << response.as_string() << endl;
	}
	
	stream.reset();
	rediscpp::value response = rediscpp::execute( (*stream), "select", "1");
```

This process works without problems .

But if I enable redis authentication (CONFIG SET requirepass "mypass"  or in redis.conf file) ,
the following code generates a SEG SIGNAL  .

```
auto stream = rediscpp::make_stream("127.0.0.1", "6379");
auto response = rediscpp::execute( (*stream), "AUTH", "mypass");
response = rediscpp::execute( (*stream), "select", "1");

cout << response.as_string() << endl; // Here is OK
stream.reset();
response = rediscpp::execute( (*stream), "AUTH", "mypass"); // <- Here segmentation fault

```

My solution is to re-create the stream ( stream = rediscpp::make_stream("127.0.0.1", "6379"); ) 
but I think that could be a BUG and I have preferred to report it to collaborate with this fantastic project.
Best regards,
Roni

**Comment by tdv** [comment]
Hi.

According to the doc you need to call 'AUTH' in a connection before any other command will be sent and having reconnected the connection you need to send 'AUTH' again like a very first command into an opened (new) stream.
Likely, that will solve your issue. The library is only a low-level tool for the command sending and receiving answers.

https://redis.io/commands/auth/

Likely, a common rule is every  connection has to start with 'AUTH' command sending.

Good luck.
Regards

**Comment by tdv** [comment]
```cpp
stream.reset();
response = rediscpp::execute( (*stream), "AUTH", "mypass"); // <- Here segmentation fault

```

stream.reset() sets the stream as a nullptr and next call  rediscpp::execute( (*stream) is fatal because there is used the nullptr instead real instance of the stream.
