### ISSUE TITLE
elif with no expression

### ISSUE THREAD

**Issue by Goksel12211** [tdv/redis-cpp#27]
## There are elif condition without expression. You can replace  `elif` with `else` to fix. <html>:thumbsup:

<br class="Apple-interchange-newline">
</body>
</html>

/redis-cpp/detail/config.h:19:6: error: #elif with no expression
![image](https://user-images.githubusercontent.com/77725216/213705984-076105d0-4b6f-4fdd-9452-e1e84d631206.png)

**Comment by tdv** [comment]
Hello.
Thanks for an issue opening.
I've just fixed.
Regards.
