### ISSUE TITLE
CLIENT REPLY

### ISSUE THREAD

**Issue by md0101** [tdv/redis-cpp#28]
Thanks for sharing your library. 

I am assuming the set command is blocking until it receives a response from the server
To improve performance I would like to remove client reply but this command does not work 

auto response = rediscpp::execute(*stream, "CLIENT REPLY", "OFF");

any suggestions how I can achieve this ?

**Comment by tdv** [comment]
Hi.
I suppose, your case might be implemented closer to the work with pipelines like in https://github.com/tdv/redis-cpp/blob/master/examples/pipeline/src/main.cpp having slightly modified that one, i.g. create a stream and start sending commands via the stream and flush the stream from time to time (for instance after a few commands sending). Drop out the response receiving from the example. I think, it will solve your issue. I haven't any other guesses how to solve the issue right away. Try to do that.
Regards.
