### ISSUE TITLE
Array return issues

### ISSUE THREAD

**Issue by NMS0** [tdv/redis-cpp#3]
Great project, very good implementation thanks for this project.
There is no other way to contact you as this is not an issue with the project but my lack of understanding a portion of the code.

I’m executing commands in MVS 2019 on windows but connecting to redis within an Ubuntu VM.  
I am primarily working with the Redis TimeSeries module (TSDB).  I have successfully ingested data into TSDB but I am having problems syntactically with the return values.  Your set and get examples for redis database within the project summarize Bulk/string replies.  However, can you please provide an example of an array type reply for commands such as HMGET?  Below I will give an example of the TS.GET command which is for the redis time series module but both HMGET and TS.GET return values are array replies.  

I’ve been studying the value.h, execute.h,  deserialization.h files and looked at your resp serialization and deserialization examples to get an understanding of the code.  I’ve looked at value.h line 83

  [[nodiscard]] bool is_array() const noexcept {
    return marker_ == resp::detail::marker::array;
  } 
But there is no corresponding return get_value for an array type?

This is what I have done so far:

#define REDISCPP_HEADER_ONLY
#include <redis-cpp/execute.h>
#include <redis-cpp/stream.h>

int main() {
  try {

    // Create Redis Connection
    auto stream = rediscpp::make_stream("localhost", "6379");

    // Variables to Create & Add Sample to Redis TimeSeries DB (TSDB)
    auto const pmc       = "TS.ADD";    // Redis cmd to create and add TSDB
    auto const key       = "MyData";    // Key
    auto const times     = "*";         // Redis Arg for auto generated time stamp
    auto const sampv     = "1";         // Redis Arg to assign sample number
    auto const cmd2      = "RETENTION"; // Redis Arg to assign Retention period of sample
    auto const retperiod = "0";         // Retention period set to 0 (Meaning, sample will persist indefinately within TSDB)
    auto const cmd3      = "LABELS";    // Redis Arg to assign Labels within TSDB
    auto const label1    = "Speed";     // Label 1 = Speed
    auto const value1    = "60 mph";    // Value assigned to Label 1
    auto const label2    = "Time";
    auto const value2    = "2 seconds";

    // Execute Command to Create & Add Sample to Redis TimeSeries DB (TSDB)
    auto response = rediscpp::execute(*stream, pmc, key, times, sampv, cmd2, retperiod, 
                                       cmd3, label1, value1, label2, value2);

    //  No problems here.  Command executes successfully and we have now added a
    //  sample to TSDB. If you have Redis TSDB installed TS.INFO MyData should
    //  show the following:

    /*  1) totalSamples
        2) (integer) 1
        3) memoryUsage
        4) (integer) 4244
        5) firstTimestamp
        6) (integer) 1592739199434
        7) lastTimestamp
        8) (integer) 1592739199434
        9) retentionTime
        10) (integer) 0
        11) chunkCount
        12) (integer) 1
        13) maxSamplesPerChunk
        14) (integer) 256
        15) labels
        16) 1)  1) "Speed"
                2) "60 mph"
            2)  1) "Time"
                2) "2 seconds"
        17) sourceKey
        18) (nil)
        19) rules
        20) (empty list or set)*/

    // Problem starts here when we want the return value in the form of an array
    // within the client. Redis documentation for TS.GET command - The returned
    // array will contain: - The last sample timestamp followed by the last
    // sample value, when the time-series contains data. - An empty array, when
    // the time-series is empty.

    // TS.GET command Variable
    auto const redisoutput = "TS.GET";

    response = rediscpp::execute(*stream, redisoutput, key);
    std::cout << "TS.GET '" << key << "': " << 
    response.as<std::string>() << std::endl; //  ---> TS.GET 'MyData': Error: bad cast  

  } catch (std::exception const &e) {
    std::cerr << "Error: " << e.what() << std::endl;
    return EXIT_FAILURE;
  }
  return EXIT_SUCCESS;
}

Any command that returns an array will have the error above :  "Error: bad cast".  Can you provide an example of an array return with a command like HMGET or TS.GET (if you use TSDB)?

Thanks.

**Comment by tdv** [comment]
Hello.

Thanks for your feedback.

Yes, the library contains methods particularly for every type, but there is no direct method for getting 'array'.

I have consciously made that decision because the 'array' could contain several different data types. Moreover, the 'array' could contain some nested data with a different structure.

According to the info above, I have not implemented such method and assume the users will use the way with a 'visitor' that you could consider in the example 'pubsub' at least, having started your research from the code like below

```
std::visit(rediscpp::resp::detail::overloaded{
    // We're wondered only an array in response.
    // Otherwise, there is an error.
    [&print_message] (rediscpp::resp::deserialization::array const &arr)
```

In that case, you'll get a possibility to react and handle each type from whole 'array' that you will have gotten at the end of request execution.

Maybe my proposal will be a little vague at first glance, but in my opinion, it's the best way to keep the flexibility of the library in order to cope with independent different use-cases having kept the easy interface of the library and approach to use.

Besides, your could consider 'resp' example. There is an approach how to work/parse with arrays for instance having gotten the ones like the response from a request.

The main tip to solve your problem is you are need to use 'visitor' for 'array' type instead of usage a direct method.

I hope, my explanation will be useful to solve your problem.

**Comment by NMS0** [comment]
> Hello.
> 
> Thanks for your feedback.
> 
> Yes, the library contains methods particularly for every type, but there is no direct method for getting 'array'.
> 
> I have consciously made that decision because the 'array' could contain several different data types. Moreover, the 'array' could contain some nested data with a different structure.
> 
> According to the info above, I have not implemented such method and assume the users will use the way with a 'visitor' that you could consider in the example 'pubsub' at least, having started your research from the code like below
> 
> ```
> std::visit(rediscpp::resp::detail::overloaded{
>     // We're wondered only an array in response.
>     // Otherwise, there is an error.
>     [&print_message] (rediscpp::resp::deserialization::array const &arr)
> ```
> 
> In that case, you'll get a possibility to react and handle each type from whole 'array' that you will have gotten at the end of request execution.
> 
> Maybe my proposal will be a little vague at first glance, but in my opinion, it's the best way to keep the flexibility of the library in order to cope with independent different use-cases having kept the easy interface of the library and approach to use.
> 
> Besides, your could consider 'resp' example. There is an approach how to work/parse with arrays for instance having gotten the ones like the response from a request.
> 
> The main tip to solve your problem is you are need to use 'visitor' for 'array' type instead of usage a direct method.
> 
> I hope, my explanation will be useful to solve your problem.

Your suggestion was most helpful.  My goal was to get an array response working before adjusting and optimising the code for my project.  I have an array response working using std::visit.  I will need to modify a little to account for the nested data structures as you have mentioned.  Your project is a great base to develop more elaborate structures. 

Thank you.

**Comment by shauningoldsby** [comment]
Hi,

Could you please post the code you wrote to print an array? I am a beginner in C++ and what you have described is beyond my abilities at this time, having spent a couple days now scratching my head. I am trying to get the array printed out that is returned by "LRANGE records 0 99".
