### ISSUE TITLE
Null Bulk String are converted to empty strings

### ISSUE THREAD

**Issue by jean343** [tdv/redis-cpp#5]
If I get a non-existing key with the command
```
rediscpp::value val = rediscpp::execute(*stream, "get", "non existing key");
```

The server returns a `Null Bulk String`, but there is no way to differentiate it from an empty string. The variable `is_null_` is set to true, but `empty()` returns false.

Thanks

**Comment by tdv** [comment]
Hello.
Thank you for the request.
I've just fixed that.
Please, try to use and report the result.
Regards.

**Comment by jean343** [comment]
Thank you so much for the addition, is the preferred way to check for null to add a try/catch?

I wrote a simple wrapper for the get method, but the method `rediscpp::value::is_null` is private. I could add a try/catch, but I would prefer something built in.
```
    std::optional<std::string_view> get(std::string& key) {
            rediscpp::value val = rediscpp::execute(*stream, "get", key);
            if (rediscpp::value::is_null(val)) {
                return std::nullopt;
            }
            return val.as_string();
    }
```

**Comment by tdv** [comment]
The common approach to handle some exceptional cases in this library is a work with exceptions almost throughout (by design). But you can make a fork and tailor that to your needs as well.

Regards.

**Comment by jean343** [comment]
Thank for your response.
I would argue that obtaining a null value is not an exceptional case as I'm checking if the key exists in a `get` command.
It's much more efficient to do one `get` rather than `exist` and then a `get`. Also, calling `exist` might return true, then `get` might return (nil) if the key was removed.

**Comment by tdv** [comment]
Your needs can be satisfied by the solution which you can create out of the box not having changed any code line of the library.

For instance, you can write something like below

```cpp
        auto val = rediscpp::execute(*stream, "get", "any_key");
        std::visit(rediscpp::resp::detail::overloaded{
                    [] (auto const &) { throw std::bad_cast(); },
                    [] (rediscpp::resp::deserialization::bulk_string const &str)
                    {
                        if (str.is_null())
                            std::cout << "Null" << std::endl;
                        else
                           std::cout << "Val: " << str.get() << std::endl;
                    }
                }, val.get());
```

Or maybe write your own convenient wrapper for your project.

In general, the library will hold approach which is based on exceptions

Regards.

**Comment by jean343** [comment]
Would it be possible to add a helper `is_null()` to the `rediscpp::value` itself?

I'd like to do
```
    rediscpp::value val = rediscpp::execute(*stream, "get", key);
    if(val.is_null())
        // cache miss
```

Thank you!
I will try your option above as well.

**Comment by tdv** [comment]
According to RESP, Null is not available for all types. For instance, you can't expect Null for an integer value or for an error message. Null is available only for 'bulk_string' and 'array' (I'm not sure about 'simple_string'). Been designing the library I try to convey the most common API and everybody can tailor that to its needs by writing some wrappers which might not be flexible for all Redis methods.
The library gives a specious field for creating something over the one in order to cover its needs.
Hopefully, you've got me and my idea.
Regards.

**Comment by jean343** [comment]
Thank you for your explanation,

I prefer catching an exception over writing the std::visit code, converting NULL to an empty string would be an error in the first place.

I will update my code, thanks.

**Comment by slhck** [comment]
@jean343 Stuck with the same issue, would you mind sharing the code you ended up using to handle nonexisting keys in `GET`?

**Comment by jean343** [comment]
I ended up doing

```
        rediscpp::value val = rediscpp::execute(stream, "get", key);
        try {
            return std::string(val.as_string());
        }
        catch (std::exception &) {
            // Catch for null
            return std::nullopt;
        }
```

**Comment by valmat** [comment]
> @jean343 Stuck with the same issue, would you mind sharing the code you ended up using to handle nonexisting keys in `GET`?
According to tdv 's advice here's my my implementation. It works fine.
```c++
std::optional<std::string> Cacher::get(std::string_view key)
{
    auto response = rediscpp::execute(*_stream, "get", key);
    if(response.empty() || !response.is_string()) {
        return {};
    }

    std::optional<std::string> result{};
    std::visit(rediscpp::resp::detail::overloaded{
        [] (auto const &) { throw std::bad_cast(); },
        [&result] (const rediscpp::resp::deserialization::bulk_string &str)
        {
            if (!str.is_null()) {
                result = str.get();
            }
        }
    }, response.get());
    
    return result;
}
```
