### ISSUE TITLE
Read array including empty values fails

### ISSUE THREAD

**Issue by peakschris** [tdv/redis-cpp#9]
This is a great library, thank you for sharing this. I think I may have found an issue with rediscpp with MGET where some keys are empty strings (not null). The fix below solves the issue for me.

MGET key1 key2 key3 key4 key5

BEGIN STREAM RETURN
*5
$1109
<1109 chars of key information>
$0

$0

$0

$0

END STREAM RETURN

The fix is in binary_data, to handle items with length 0 as valid data (replace existing code with bold-section):

    binary_data(std::istream &stream)
    {
        std::string string;
        std::getline(stream, string);
        auto const length = std::stoll(string);
        **if (length < 0)
        {
            is_null_ = true;
            return;
        }**
        data_.resize(static_cast<typename buffer_type::size_type>(length));
        stream.read(&data_[0], length);
        std::getline(stream, string);
    }

**Comment by tdv** [comment]
Hi.

Thanks for the issue and fix.

I've just fixed / added that for c++ 17 version and c++ 11 backport.

Regards.
